version: '3'

set:
  - errexit
  - nounset
  - pipefail

includes:
  kind: ./tasks/kind.yaml
  bootstrap-registry: ./tasks/bootstrap-registry.yaml
  metallb: ./tasks/metallb.yaml
  cloudnative-pg: ./tasks/cloudnative-pg.yaml
  cert-manager: ./tasks/cert-manager.yaml
  cosi: ./tasks/cosi.yaml
  s3gw: ./tasks/s3gw.yaml
  harbor: ./tasks/harbor.yaml
  ntnx-objects: ./tasks/ntnx-objects.yaml

vars:
  GIT_REPO_ROOT:
    sh: git rev-parse --show-toplevel
  GIT_REPO_NAME:
    sh: basename {{.GIT_REPO_ROOT}}
  KIND_CLUSTER_NAME: "{{.GIT_REPO_NAME}}"
  MINDTHEGAP_VERSION:
    sh: gh release view --repo mesosphere/mindthegap --json tagName --jq '.tagName'
  REGISTRY_NAMESPACE: ncr-system
  KUBECONFIG: "{{.GIT_REPO_ROOT}}/kubeconfig"

env:
  KUBECONFIG: "{{.KUBECONFIG}}"
  REGISTRY_NAMESPACE: "{{.REGISTRY_NAMESPACE}}"

tasks:
  run-demo:
    cmds:
      - task: bootstrap-registry:create-image-bundle
      - task: kind:create
      - task: bootstrap-registry:deploy
      - task: metallb:deploy
      - task: metallb:configure-ipaddresspool
      - task: cert-manager:deploy
      - task: cloudnative-pg:deploy-operator
      - task: cosi:deploy
      - task: s3gw:deploy
      - task: s3gw:create-cosi-bucketclass
      - task: harbor:create-s3gw-bucket
      - task: harbor:create-redis-cluster
      - task: harbor:create-postgresql-cluster
      - task: harbor:deploy
      - task: harbor:seed
      - task: harbor:switch-to-harbor
      - task: bootstrap-registry:delete

  cleanup:
    cmds:
      - cmd: rm -f {{.GIT_REPO_ROOT}}/bootstrap-registry/bootstrap-images.tar
      - task: kind:delete
