version: '3'

set:
  - errexit
  - nounset
  - pipefail

includes:
  kind: ./tasks/kind.yaml
  registry: ./tasks/registry.yaml
  cloudnativepg: ./tasks/cloudnativepg.yaml
  cert-manager: ./tasks/cert-manager.yaml
  s3gw: ./tasks/s3gw.yaml
  harbor: ./tasks/harbor.yaml

vars:
  GIT_REPO_ROOT:
    sh: git rev-parse --show-toplevel
  GIT_REPO_NAME:
    sh: basename {{.GIT_REPO_ROOT}}
  KIND_CLUSTER_NAME: "{{.GIT_REPO_NAME}}"
  LATEST_MINDTHEGAP_VERSION:
    sh: gh release list --repo mesosphere/mindthegap --limit 1 --json name --jq '.[0].name'
  REGISTRY_NAMESPACE: ncr-system

env:
  KUBECONFIG:
    sh: echo "$(git rev-parse --show-toplevel)/kubeconfig"
  REGISTRY_NAMESPACE: "{{.REGISTRY_NAMESPACE}}"

tasks:
  run-demo:
    cmds:
      - task: registry:create-bootstrap-image-bundle
      - task: kind:create
      - task: registry:deploy-bootstrap-registry
      - task: cert-manager:deploy
      - task: cloudnativepg:deploy-operator
      - task: s3gw:deploy
      - task: s3gw:create-cosi-bucketclass
      - task: harbor:create-s3-bucket
      - task: harbor:create-ca
      - task: harbor:create-redis-cluster
      - task: harbor:create-postgresql-cluster
  cleanup:
    cmds:
      - task: kind:delete
