version: '3'

vars:
  CLOUDNATIVEPG_CHART_REPO: https://cloudnative-pg.github.io/charts
  CLOUDNATIVEPG_CHART_VERSION:
    sh: helm show chart --repo '{{.CLOUDNATIVEPG_CHART_REPO}}' cloudnative-pg | gojq --yaml-input -r '.version'
  CLOUDNATIVEPG_CLUSTER_CHART_VERSION:
    sh: helm show chart --repo '{{.CLOUDNATIVEPG_CHART_REPO}}' cluster | gojq --yaml-input -r '.version'

tasks:
  deploy-operator:
    cmds:
      - cmd: |
          helm upgrade --install cnpg cloudnative-pg \
            --repo '{{.CLOUDNATIVEPG_CHART_REPO}}' \
            --version '{{.CLOUDNATIVEPG_CHART_VERSION}}' \
            --namespace cnpg-system \
            --create-namespace \
            --wait --wait-for-jobs
    status:
      - helm get metadata --namespace cnpg-system cnpg --output json | gojq -e '.version == "{{.CLOUDNATIVEPG_CHART_VERSION}}" and .status == "deployed"'
