version: '3'

vars:
  VALKEY_CHART_OCI_URL: oci://ghcr.io/hyperspike/valkey-operator
  VALKEY_VERSION:
    sh: gh release list --repo hyperspike/valkey-operator --limit 1 --json tagName --jq '.[0].tagName'
  VALKEY_VALUES_FILE: "{{.GIT_REPO_ROOT}}/helm-values/valkey-operator.yaml"

tasks:
  deploy-operator:
    cmds:
      - cmd: |
          helm upgrade --install valkey-operator '{{.VALKEY_CHART_OCI_URL}}' \
            --version '{{.VALKEY_VERSION}}-chart' \
            --values '{{.VALKEY_VALUES_FILE}}' \
            --namespace valkey-operator-system \
            --create-namespace \
            --wait --wait-for-jobs \
            --post-renderer sed --post-renderer-args 's|/manager|/ko-app/cmd|'
    status:
      - "helm get metadata --namespace valkey-operator-system valkey-operator | grep -qi '^version: {{.VALKEY_VERSION}}-chart$'"
